version: '3.8'
services:
  mongodb-env:
    image: mongo:latest
    container_name: mongodb-env
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: fajar
      MONGO_INITDB_ROOT_PASSWORD: Fajar123_
      MONGO_INITDB_DATABASE: admin
    networks:
      - network_example
networks:
  network_example:
    name: network_example
    driver: bridge
