version: '3.8'
services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: fajar
      MONGO_INITDB_ROOT_PASSWORD: fajar123_
      MONGO_INITDB_DATABASE: admin
    networks:
      - mongo_network
  mongodb-express:
    image: mongo-express:latest
    container_name: mongodb-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: fajar
      ME_CONFIG_MONGODB_ADMINPASSWORD: fajar123_
      ME_CONFIG_MONGODB_SERVER: mongodb-example
    networks:
      - mongo_network
    depends_on:
      - mongodb-example
networks: 
  mongo_network:
    name: mongo_network
    driver: bridge
